name: room
channels:
  - pytorch
  - defaults
  - nvidia
  - conda-forge
dependencies:
  - python=3.9.17
  - pip=20.3
  - cudatoolkit=11.8
  - cuda=11.8.0
  - cuda-cudart=11.8.89
  - pytorch=2.0.1=*cuda*
  - pytorch-cuda=11.8
  - torchvision=0.15.2=*cu118
  - ipykernel=6.25.0
  - voluptuous=0.13.1
  - matplotlib=3.8.0
  - rich=13.6.0
  - flask=2.2.2
  - werkzeug=2.2.3
  - pip:
      - accelerate==0.18.0
      - albumentations==1.3.0
      - diffusers==0.21.4
      - polars==0.19.7
      - opencv-python==4.7.0.68
      - omegaconf==2.3.0
      - pytorch-lightning==1.9.0
      - einops==0.6.0
      - transformers==4.26.0
      - tensorboard==2.12.0
      - safetensors==0.3.1
      - Flask-Cors==1.10.3
